<a href="https://colab.research.google.com/github/SalmanOkz/Artificial-Intelligence/blob/main/NLP_lab_09.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Lab Session 10

# NLP Lab: Sentiment Analysis

## Objective
In this lab, we will:
- Clean text data
- Convert text into numerical features
- Train a machine learning model
- Predict sentiment (Positive/Negative)

## Tools
- Python
- scikit-learn
- NLTK

In [1]:
import pandas as pd
import numpy as np

import nltk
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize

from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import CountVectorizer, TfidfVectorizer
from sklearn.naive_bayes import MultinomialNB
from sklearn.metrics import accuracy_score

nltk.download('punkt')
nltk.download('stopwords')

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt.zip.
[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.

True

In [2]:
data = {
    "text": [
        "I love this product",
        "This is amazing",
        "I am very happy",
        "I hate this",
        "This is terrible",
        "I am very sad",
        "Absolutely fantastic experience",
        "Worst service ever",
        "I enjoyed this a lot",
        "Not good at all"
    ],
    "label": [1,1,1,0,0,0,1,0,1,0]
}

df = pd.DataFrame(data)
df.head()

                  text  label
0  I love this product      1
1      This is amazing      1
2      I am very happy      1
3          I hate this      0
4     This is terrible      0

In [6]:
import nltk

nltk.download('punkt')
nltk.download('punkt_tab')
nltk.download('stopwords')

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package punkt_tab to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt_tab.zip.
[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

True

In [7]:
stop_words = set(stopwords.words('english'))

def preprocess(text):
    tokens = word_tokenize(text.lower())
    filtered = [word for word in tokens if word.isalnum() and word not in stop_words]
    return " ".join(filtered)

df["clean_text"] = df["text"].apply(preprocess)
df

                              text  label                       clean_text
0              I love this product      1                     love product
1                  This is amazing      1                          amazing
2                  I am very happy      1                            happy
3                      I hate this      0                             hate
4                 This is terrible      0                         terrible
5                    I am very sad      0                              sad
6  Absolutely fantastic experience      1  absolutely fantastic experience
7               Worst service ever      0               worst service ever
8             I enjoyed this a lot      1                      enjoyed lot
9                  Not good at all      0                             good

In [8]:
vectorizer = CountVectorizer()

X = vectorizer.fit_transform(df["clean_text"])
y = df["label"]

print(X.toarray())

[[0 0 0 0 0 0 0 0 0 0 1 1 0 0 0 0]
 [0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0]
 [1 0 0 0 1 1 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 1 0 0 0 0 0 0 0 0 0 1 0 1]
 [0 0 1 0 0 0 0 0 0 1 0 0 0 0 0 0]
 [0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0]]

In [9]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [10]:
model = MultinomialNB()
model.fit(X_train, y_train)

MultinomialNB()

In [11]:
y_pred = model.predict(X_test)
print("Accuracy:", accuracy_score(y_test, y_pred))

Accuracy: 0.0

In [12]:
def predict_sentiment(text):
    cleaned = preprocess(text)
    vector = vectorizer.transform([cleaned])
    prediction = model.predict(vector)

    return "Positive 😊" if prediction[0] == 1 else "Negative 😠"

print(predict_sentiment("I really love this"))
print(predict_sentiment("This is the worst thing ever"))

Positive 😊
Negative 😠

In [13]:
tfidf = TfidfVectorizer()

X_tfidf = tfidf.fit_transform(df["clean_text"])

X_train, X_test, y_train, y_test = train_test_split(X_tfidf, y, test_size=0.2, random_state=42)

model.fit(X_train, y_train)
y_pred = model.predict(X_test)

print("TF-IDF Accuracy:", accuracy_score(y_test, y_pred))

TF-IDF Accuracy: 0.0

## Exercises

1. Add 5 more sentences to the dataset  
2. Test your own sentences  
3. Try removing stopwords step and compare results  
4. Compare BoW vs TF-IDF accuracy

## Discussion

- Why do we clean text?
- Why do machines need numbers?
- Why is the model sometimes wrong?
- How can we improve it?

## Next Step
Modern NLP uses models like BERT and GPT.